version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile-jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agents:/agents
    ports:
      - 8080:8080
      - 50000:50000

  # agent-chrome:
  #   build:
  #     context: .
  #     dockerfile: ./agents/Dockerfile-chrome
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 6080:80
