version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile-jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agents:/agents
    ports:
      - 6080:8080
      - 50000:50000
